function net = trainCNN(XTrain, YTrain, layers)
    % Create validation set (20%)
    cv = cvpartition(YTrain, 'Holdout', 0.2);
    
    options = trainingOptions('adam', ...
        'MaxEpochs', 50, ...  %was 50
        'MiniBatchSize', 128, ... %was 128
        'ValidationData', {XTrain(:,:,:,cv.test), YTrain(cv.test)}, ...
        'ValidationFrequency', 30, ...
        'InitialLearnRate', 0.001, ...    %was 0.001
        'LearnRateSchedule', 'piecewise', ...
        'LearnRateDropFactor', 0.5, ...
        'LearnRateDropPeriod', 10, ...
        'L2Regularization', 0.001, ...   %was 0.001
        'Shuffle', 'every-epoch', ...
        'Verbose', true, ...
        'Plots', 'training-progress');
    
    net = trainNetwork(XTrain(:,:,:,cv.training), YTrain(cv.training), layers, options);
end